.TH REMOTEX "1" "December 2025" "RemoteX 1.0.0" "User Commands"
.SH NAME
remotex \- High-Performance SSH Management CLI
.SH SYNOPSIS
.B remotex
.RI [ OPTIONS ]
.RI [ COMMAND ]
.RI [ ARGS ]
.SH DESCRIPTION
RemoteX is a high-performance command-line tool for managing SSH servers and executing commands remotely. It supports parallel execution, server groups, command aliases, and more.
.SH OPTIONS
.TP
.BI \-v ", " \-\-verbose
Verbose output
.TP
.BI \-\-debug
Debug mode with detailed logging
.TP
.BI \-\-version
Show version and exit
.TP
.BI \-\-help
Show help message
.SH COMMANDS
.TP
.B list
List all configured servers
.TP
.B add
Add a new server to SSH config
.TP
.B exec
Execute a command on a remote server
.TP
.B connect
Open an interactive shell session
.TP
.B exec-all
Execute a command on all servers in parallel
.TP
.B exec-multi
Execute a command on specific servers
.TP
.B exec-group
Execute a command on all servers in a group
.TP
.B history
Manage command history
.TP
.B tunnel
Manage SSH tunnels
.SH EXAMPLES
.PP
List all servers:
.RS
.B remotex list
.RE
.PP
Execute command on server:
.RS
.B remotex exec web01 "uptime"
.RE
.PP
Execute on all servers in parallel:
.RS
.B remotex exec-all "df -h" --parallel 10
.RE
.SH AUTHOR
Sagar Memane <sagarmemane135@github.com>
.SH "SEE ALSO"
Full documentation: https://github.com/sagarmemane135/remotex
